"""Allow null values for spaceship fields

Revision ID: 99623d2b36ea
Revises: b61938284f27
Create Date: 2024-09-23 09:20:12.753821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99623d2b36ea'
down_revision: Union[str, None] = 'b61938284f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaceship', sa.Column('speed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaceship', 'speed')
    # ### end Alembic commands ###
